export default {
    // icloud button disabled的颜色和border颜色一样
    '--btn-disable-bg': 'var(--theme-border-color-disabled)',
    '--btn-disable-border': 'var(--theme-border-color-disabled)',
    '--btn-disable-color': 'var(--color-gray-7)',
    // type default
    '--btn-default-bg': 'var(--theme-component-bg)',
    '--btn-default-border-color': 'var(--theme-border-color-base)',
    '--btn-default-color': 'var(--theme-text-color)',
    '--btn-default-active-bg': 'var(--color-brand-1)',
    '--btn-default-active-border-color': 'var(--theme-primary-color)',
    '--btn-default-active-color': 'var(--theme-primary-color)',
    '--btn-default-disable-bg': 'var(--btn-disable-bg)',
    '--btn-default-disable-border-color': 'var(--btn-disable-border)',
    '--btn-default-disable-color': 'var(--btn-disable-color)',
    '--btn-default-focus-bg': 'var(--theme-component-bg)',
    '--btn-default-focus-border-color': 'var(--theme-primary-color)',
    '--btn-default-focus-color': 'var(--theme-primary-color)',
    '--btn-default-hover-bg': 'var(--theme-component-bg)',
    '--btn-default-hover-border-color': 'var(--theme-primary-color-hover)',
    '--btn-default-hover-color': 'var(--theme-primary-color-hover)',
    '--btn-default-loading-bg': 'var(--theme-component-bg)',
    '--btn-default-loading-border-color': 'var(--theme-primary-color)',
    '--btn-default-loading-color': 'var(--theme-primary-color)',
    // type primary
    '--btn-primary-bg': 'var(--theme-primary-color)',
    '--btn-primary-border-color': 'var(--theme-primary-color)',
    '--btn-primary-color': 'var(--color-gray-1)',
    '--btn-primary-active-bg': 'var(--color-brand-7)',
    '--btn-primary-active-border-color': 'var(--color-brand-7)',
    '--btn-primary-active-color': 'var(--color-gray-1)',
    '--btn-primary-disable-bg': 'var(--btn-disable-bg)',
    '--btn-primary-disable-border-color': 'var(--btn-disable-border)',
    '--btn-primary-disable-color': 'var(--btn-disable-color)',
    '--btn-primary-focus-bg': 'var(--theme-primary-color)',
    '--btn-primary-focus-border-color': 'var(--theme-primary-color)',
    '--btn-primary-focus-color': 'var(--color-gray-1)',
    '--btn-primary-hover-bg': 'var(--theme-primary-color-hover)',
    '--btn-primary-hover-border-color': 'var(--theme-primary-color-hover)',
    '--btn-primary-hover-color': 'var(--color-gray-1)',
    '--btn-primary-loading-bg': 'var(--theme-primary-color)',
    '--btn-primary-loading-border-color': 'var(--theme-primary-color)',
    '--btn-primary-loading-color': 'var(--color-gray-1)',
    // type link
    '--btn-link-bg': 'transparent',
    '--btn-link-border-color': 'transparent',
    '--btn-link-color': 'var(--theme-text-color)',
    '--btn-link-active-bg': 'transparent',
    '--btn-link-active-border-color': 'transparent',
    '--btn-link-active-color': 'var(--theme-primary-color-active)',
    '--btn-link-disable-bg': 'transparent',
    '--btn-link-disable-border-color': 'transparent',
    '--btn-link-disable-color': 'var(--btn-disable-color)',
    '--btn-link-focus-bg': 'transparent',
    '--btn-link-focus-border-color': 'transparent',
    '--btn-link-focus-color': 'var(--theme-primary-color)',
    '--btn-link-hover-bg': 'transparent',
    '--btn-link-hover-border-color': 'transparent',
    '--btn-link-hover-color': 'var(--theme-primary-color)',
    '--btn-link-loading-bg': 'transparent',
    '--btn-link-loading-border-color': 'transparent',
    '--btn-link-loading-color': 'var(--btn-link-focus-color)',
    // type icon
    '--btn-icon-bg': 'transparent',
    '--btn-icon-border-color': 'transparent',
    '--btn-icon-color': 'var(--theme-text-color)',
    '--btn-icon-active-bg': 'transparent',
    '--btn-icon-active-border-color': 'transparent',
    '--btn-icon-active-color': 'var(--theme-primary-color-active)',
    '--btn-icon-disable-bg': 'var(--btn-disable-bg)',
    '--btn-icon-disable-border-color': 'var(--btn-disable-border)',
    '--btn-icon-disable-color': 'var(--btn-disable-color)',
    '--btn-icon-focus-bg': 'transparent',
    '--btn-icon-focus-border-color': 'transparent',
    '--btn-icon-focus-color': 'var(--theme-primary-color)',
    '--btn-icon-hover-bg': 'transparent',
    '--btn-icon-hover-border-color': 'transparent',
    '--btn-icon-hover-color': 'var(--theme-primary-color-hover)',
    '--btn-icon-loading-bg': 'var(--btn-icon-focus-bg)',
    '--btn-icon-loading-border-color': 'var(--btn-icon-focus-border-color)',
    '--btn-icon-loading-color': 'var(--btn-icon-focus-color)',
    // type strong
    '--btn-strong-bg': 'var(--theme-component-bg)',
    '--btn-strong-border-color': 'var(--theme-primary-color)',
    '--btn-strong-color': 'var(--theme-primary-color)',
    '--btn-strong-active-bg': 'var(--btn-default-active-bg)',
    '--btn-strong-active-border-color': 'var(--btn-default-active-border-color)',
    '--btn-strong-active-color': 'var(--btn-default-active-border-color)',
    '--btn-strong-disable-bg': 'var(--btn-disable-bg)',
    '--btn-strong-disable-border-color': 'var(--btn-disable-border)',
    '--btn-strong-disable-color': 'var(--btn-disable-color)',
    '--btn-strong-focus-bg': 'var(--btn-default-focus-bg)',
    '--btn-strong-focus-border-color': 'var(--btn-default-focus-border-color)',
    '--btn-strong-focus-color': 'var(--btn-default-focus-color)',
    '--btn-strong-hover-bg': 'var(--btn-default-hover-bg)',
    '--btn-strong-hover-border-color': 'var(--btn-default-hover-border-color)',
    '--btn-strong-hover-color': 'var(--btn-default-hover-color)',
    '--btn-strong-loading-bg': 'var(--btn-default-loading-bg)',
    '--btn-strong-loading-border-color': 'var(--btn-default-loading-border-color)',
    '--btn-strong-loading-color': 'var(--btn-default-loading-color)',
    // other properties
    '--btn-border-radius-base': '0px',
    '--btn-link-margin': '0',
    '--btn-link-padding': '4px 15px',
    '--btn-loading-text-display': 'inline',
    '--btn-link-text-decoration': 'none',
};
