export default {
    '--collapse-content-bg': 'var(--color-gray-1)',
    '--collapse-header-bg': 'var(--color-gray-3)',
    '--collapse-disabled-color': 'var(--theme-disabled-color)',
    '--collapse-expand-icon-color': 'var(--color-gray-7)',
    '--collapse-expand-icon-bg': 'transparent',
    '--collapse-border-color': 'none',
    '--collapse-bg': 'transparent',
    '--collapse-header-font-weight': '400',
    '--collapse-header-font-size': '12px',
    '--collapse-header-height': '40px',
    '--collapse-content-box-padding-top': '12px',
    '--collapse-content-box-padding-bottom': '12px',
    '--collapse-arrow-top': '12px',
    '--collpase-item-header-margin-bottom': '4px',
};
