export default {
    '--radio-border-color': 'var(--color-gray-7)',
    '--radio-hover-border-color': 'var(--theme-primary-color)',
    '--radio-hover-bg': 'var(--theme-component-bg)',
    '--radio-checked-color': 'var(--theme-primary-color)',
    '--radio-disabled-bg': 'var(--color-gray-3)',
    '--radio-disabled-dot-color': 'var(--color-gray-6)',
    '--radio-disabled-border-color': 'var(--color-gray-4)',
    '--radio-button-disabled-color': 'var(--color-gray-6)',
    '--radio-button-disabled-border-color': 'var(--color-gray-3)',
    '--radio-button-disabled-bg': 'var(--color-gray-4)',
    '--radio-button-hover-color': 'var(--theme-primary-color-hover)',
    '--radio-hover-border-zindex': 2,
    '--radio-span-padding-horizontal': '5px',
    '--radio-wrapper-margin-right': '15px',
};
