export default {
    '--radio-border-color': 'var(--color-gray-7)',
    '--radio-hover-border-color': 'var(--theme-primary-color-hover)',
    '--radio-hover-bg': 'var(--theme-component-bg)',
    '--radio-checked-color': 'var(--theme-primary-color)',
    '--radio-disabled-bg': 'var(--color-gray-2)',
    '--radio-disabled-dot-color': 'var(--color-brand-2)',
    '--radio-disabled-border-color': 'var(--color-gray-5)',
    '--radio-button-checked-disabled-border-color': 'var(--color-brand-2)',
    '--radio-button-checked-disabled-bg': 'var(--color-brand-2)',
    '--radio-button-checked-disabled-color': '#adcaff',
    '--radio-button-disabled-color': 'var(--color-gray-6)',
    '--radio-button-disabled-border-color': 'var(--color-gray-5)',
    '--radio-button-disabled-bg': 'var(--color-gray-2)',
    '--radio-button-hover-color': 'var(--theme-primary-color-hover)',
    '--radio-active-border-color': 'var(--theme-primary-color-active)',
    '--radio-hover-border-zindex': 2,
    '--radio-span-padding-horizontal': '8px',
    '--radio-wrapper-margin-right': '12px',
    '--radio-top': '3px',
};
