export default {
    '--tag-check-border': 'var(--color-brand-4)',
    '--tag-default-bg': 'var(--color-gray-3)',
    '--tag-font-color': 'var(--color-gray-9)',
    '--tag-blue-color': 'var(--color-brand-1)',
    '--tag-green-color': 'var(--color-success-1)',
    '--tag-purple-color': 'var(--color-purple-1)',
    '--tag-red-color': 'var(--color-error-1)',
    '--tag-yellow-color': 'var(--color-warning-1)',
    '--tag-blue-bg-color': 'var(--color-brand-1)',
    '--tag-blue-solid-bg-color': 'var(--color-brand-6)',
    '--tag-blue-font-color': 'var(--color-brand-6)',
    '--tag-green-bg-color': 'var(--color-success-1)',
    '--tag-green-solid-bg-color': 'var(--color-success-6)',
    '--tag-green-font-color': 'var(--color-success-6)',
    '--tag-red-bg-color': 'var(--color-error-1)',
    '--tag-red-solid-bg-color': 'var(--color-error-6)',
    '--tag-red-font-color': 'var(--color-error-6)',
    '--tag-yellow-bg-color': 'var(--color-warning-1)',
    '--tag-yellow-font-color': 'var(--color-warning-6)',
    '--tag-yellow-solid-bg-color': 'var(--color-warning-6)',
    '--tag-padding': '0 5px',
    '--tag-icon-maring-horizontal': '10px',
    '--tag-icon-color': 'var(--color-gray-7)',
};
