export default {
    // eslint-disable-next-line max-len
    '--theme-font-family': '-apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", "Arial", "PingFangSC-Regular", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
    '--theme-bg-color-base': 'var(--color-gray-4)',
    '--theme-bg-color-light': 'var(--color-brand-1)',
    '--theme-body-bg': 'var(--color-gray-1)',
    '--theme-border-color-base': 'var(--color-gray-4)',
    '--theme-border-color-disabled': 'var(--color-gray-4)',
    '--theme-border-color-inverse': '#fff',
    '--theme-border-color-split': 'var(--color-gray-4)',
    '--theme-border-focus-color': 'var(--theme-primary-color)',
    '--theme-color-text': 'var(--color-gray-8)',
    '--theme-component-bg': 'var(--color-gray-1)',
    '--theme-component-focus-box-shadow': 'none',
    '--theme-disabled-bg': 'var(--color-gray-2)',
    '--theme-disabled-color': 'var(--color-gray-5)',
    '--theme-error-color-active': 'var(--color-error-7)',
    '--theme-error-color-hover': 'var(--color-error-5)',
    '--theme-error-color': 'var(--color-error-6)',
    '--theme-heading-color': 'var(--color-gray-9)',
    '--theme-highlight-color': 'var(--color-error-5)',
    '--theme-icon-color': 'var(--color-gray-6)',
    '--theme-info-color-active': 'var(--color-info-7)',
    '--theme-info-color-hover': 'var(--color-info-5)',
    '--theme-info-color': 'var(--color-info-6)',
    '--theme-outline-color': 'var(--color-brand-4)',
    '--theme-placeholder-color': 'var(--color-gray-5)',
    '--theme-primary-color-active': 'var(--color-brand-7)',
    '--theme-primary-color-hover': 'var(--color-brand-5)',
    '--theme-primary-color': 'var(--color-brand-6)',
    '--theme-processing-color': 'var(--color-brand-6)',
    '--theme-secondary-color-active': 'var(--color-brand-3)',
    '--theme-secondary-color-hover': 'var(--color-brand-1)',
    '--theme-secondary-color': 'var(--color-brand-2)',
    '--theme-success-color-active': 'var(--color-success-7)',
    '--theme-success-color-hover': 'var(--color-success-5)',
    '--theme-success-color': 'var(--color-success-6)',
    '--theme-text-color-secondary': 'var(--color-gray-8)',
    '--theme-text-color': 'var(--color-gray-9)',
    '--theme-warning-color-active': 'var(--color-warning-7)',
    '--theme-warning-color-hover': 'var(--color-warning-5)',
    '--theme-warning-color': 'var(--color-warning-6)',
    '--item-hover-bg': 'var(--color-gray-3)',
    '--osui-icon-size': '16px',
};
