import {ThemeConfig} from 'antd';

type AntdToken = Required<ThemeConfig>['token'];

/* eslint-disable max-len */
export const acud: AntdToken = {
    borderRadius: 4,
    borderRadiusSM: 2,
    boxShadowSecondary: `
        0 3px 6px -4px rgba(0, 0, 0, .12),
        0 6px 16px 0 rgba(0, 0, 0, .08),
        0 9px 28px 8px rgba(0, 0, 0, .05)
    `,
    colorBgBase: '#F7F7F9',
    colorBgContainer: '#FFFFFF',
    colorBgContainerDisabled: '#F7F7F9',
    colorBgElevated: '#FFFFFF',
    colorBorder: '#E8E9EB',
    colorError: '#F33E3E',
    colorErrorActive: '#CC292E',
    colorErrorBg: '#fff2f0',
    colorErrorBorder: '#ffccc7',
    colorErrorHover: '#FF6966',
    colorHighlight: '#F33E3E',
    colorIcon: 'inherit',
    colorIconHover: 'rgba(0, 0, 0, 0.75)',
    colorInfo: '#2468F2',
    colorInfoBg: ' var(--info-color-deprecated-bg);',
    colorInfoBorder: ' var(--info-color-deprecated-border);',
    colorLink: '#2468F2',
    colorLinkActive: '#144BCC',
    colorLinkHover: '#528EFF',
    colorPrimary: '#2468F2',
    colorPrimaryActive: '#5971e7',
    colorPrimaryBg: '#eef0fd',
    colorPrimaryBgHover: '#dce1fa',
    colorPrimaryBorder: ' var(--primary-3);',
    colorPrimaryBorderHover: ' var(--primary-4);',
    colorPrimaryHover: '#528EFF',
    colorPrimaryText: ' var(--primary-9);',
    colorPrimaryTextActive: ' var(--primary-10);',
    colorPrimaryTextHover: ' var(--primary-8);',
    colorSplit: '#E8E9EB',
    colorSuccess: '#30BF13',
    colorSuccessActive: '#1B9908',
    colorSuccessBg: '#f6ffed',
    colorSuccessBgHover: '#54CC39',
    colorSuccessBorder: '#b7eb8f',
    colorText: '#151B26',
    colorTextDisabled: '#B8BABF',
    colorTextHeading: '#151B26',
    colorTextPlaceholder: '#B8BABF',
    colorTextSecondary: '#5C5F66',
    colorWarning: '#FF9326',
    colorWarningActive: '#D97116',
    colorWarningBg: '#fffbe6',
    colorWarningBorder: '#ffe58f',
    colorWarningHover: '#FFAB52',
    colorWhite: '#fff',
    controlHeight: 32,
    controlHeightLG: 40,
    controlHeightSM: 24,
    controlItemBgActive: '#E6F0FF',
    controlItemBgHover: '#E6F0FF',
    controlOutline: '#2468F2',
    controlOutlineWidth: 0,
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", "Arial", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
    fontSize: 12,
    fontSizeHeading1: 33,
    fontSizeHeading2: 26,
    fontSizeHeading3: 21,
    fontSizeHeading4: 18,
    fontSizeHeading5: 14,
    fontSizeLG: 16,
    fontSizeSM: 12,
    lineHeight: 1.5,
    lineWidth: 1,
    margin: 16,
    marginLG: 24,
    marginSM: 12,
    marginXS: 8,
    marginXXS: 4,
    motionEaseInBack: 'cubic-bezier(0.9, 0, 0.3, 0.7)',
    motionEaseInOut: 'cubic-bezier(0.645, 0.045, 0.355, 1)',
    motionEaseInOutCirc: 'cubic-bezier(0.78, 0.14, 0.15, 0.86)',
    motionEaseInQuint: 'cubic-bezier(0.755, 0.05, 0.855, 0.06)',
    motionEaseOut: 'cubic-bezier(0.215, 0.61, 0.355, 1)',
    motionEaseOutBack: 'cubic-bezier(0.12, 0.4, 0.29, 1.46)',
    motionEaseOutCirc: 'cubic-bezier(0.08, 0.82, 0.17, 1)',
    motionEaseOutQuint: 'cubic-bezier(0.23, 1, 0.32, 1)',
    padding: 16,
    paddingLG: 24,
    paddingSM: 12,
    paddingXS: 8,
    paddingXXS: 4,
};


