export const acud = {
    'colorPrimary': '#2468F2',
    'colorPrimaryActive': '#5971e7',
    'colorInfo': '#2468F2',
    'colorInfoBg': ' var(--info-color-deprecated-bg);',
    'colorInfoBorder': ' var(--info-color-deprecated-border);',
    'colorSuccess': '#30BF13',
    'colorSuccessBgHover': '#54CC39',
    'colorSuccessActive': '#1B9908',
    'colorSuccessBg': '#f6ffed',
    'colorSuccessBorder': '#b7eb8f',
    'colorWarning': '#FF9326',
    'colorWarningHover': '#FFAB52',
    'colorWarningActive': '#D97116',
    'colorWarningBg': '#fffbe6',
    'colorWarningBorder': '#ffe58f',
    'colorError': '#F33E3E',
    'colorErrorHover': '#FF6966',
    'colorErrorActive': '#CC292E',
    'colorErrorBg': '#fff2f0',
    'colorErrorBorder': '#ffccc7',
    'colorHighlight': '#F33E3E',
    'colorWhite': '#fff',
    'colorPrimaryBg': '#eef0fd',
    'colorPrimaryBgHover': '#dce1fa',
    'colorPrimaryBorder': ' var(--primary-3);',
    'colorPrimaryBorderHover': ' var(--primary-4);',
    'colorPrimaryTextHover': ' var(--primary-8);',
    'colorPrimaryText': ' var(--primary-9);',
    'colorPrimaryTextActive': ' var(--primary-10);',
    'colorBgBase': '#F7F7F9',
    'colorBgContainer': '#FFFFFF',
    'colorBgElevated': '#FFFFFF',
    'colorSplit': '#E8E9EB',
    // eslint-disable-next-line max-len
    'fontFamily': '-apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", "Arial", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
    'colorText': '#151B26',
    'colorTextSecondary': '#5C5F66',
    'colorIcon': 'inherit',
    'colorIconHover': 'rgba(0, 0, 0, 0.75)',
    'colorTextHeading': '#151B26',
    'fontSize': 12,
    'fontSizeLG': 16,
    'fontSizeSM': 12,
    'lineHeight': 1.5,
    'borderRadius': 4,
    'borderRadiusSM': 2,
    'controlHeight': 32,
    'controlHeightLG': 40,
    'controlHeightSM': 24,
    'controlItemBgActive': '#E6F0FF',
    'controlItemBgHover': '#E6F0FF',
    'colorLink': '#2468F2',
    'colorLinkHover': '#528EFF',
    'colorLinkActive': '#144BCC',
    'colorBorder': '#E8E9EB',
    'lineWidth': 1,
    'controlOutlineWidth': 0,
    'controlOutline': '#2468F2',
    'colorTextDisabled': '#B8BABF',
    'colorBgContainerDisabled': '#F7F7F9',
    'colorBgContainerDisabled // tint(@black, 90%);': '#e6e6e6',
    'boxShadowSecondary': ' 0 3px 6px -4px rgba(0, 0, 0, .12), 0 6px 16px 0 rgba(0, 0, 0, .08),',
};

// 暂时未找到对应css变量
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const a = {
    'colorPrimaryHover': 'primary-5',
    'fontSizeHeading1': 'heading-1-size',
    'fontSizeHeading2': 'heading-2-size',
    'fontSizeHeading3': 'heading-3-size',
    'fontSizeHeading4': 'heading-4-size',
    'fontSizeHeading5': 'heading-5-size',
    'borderRadius': 'control-border-radius',
    'paddingLG': 'padding-lg',
    'padding': 'padding-md',
    'paddingSM': 'padding-sm',
    'paddingXS': 'padding-xs',
    'paddingXXS': 'padding-xss',
    'paddingSM //@padding-sm;': 'control-padding-horizontal',
    'paddingXS // @padding-xs;': 'control-padding-horizontal-sm',
    'marginLG': 'margin-lg',
    'margin': 'margin-md',
    'marginSM': 'margin-sm',
    'marginXS': 'margin-xs',
    'marginXXS': 'margin-xss',
    'motionEaseOut': 'ease-out',
    'motionEaseInOut': 'ease-in-out',
    'motionEaseOutBack': 'ease-out-back',
    'motionEaseOutCirc': 'ease-out-circ',
    'motionEaseInOutCirc': 'ease-in-out-circ',
    'motionEaseOutQuint': 'ease-out-quint',
    'motionEaseInQuint': 'ease-in-quint',
    'boxShadow': 'box-shadow-base',
    'boxShadowDrawerUp': 'shadow-1-up',
    'boxShadowDrawerDown': 'shadow-1-down',
    'boxShadowDrawerLeft': 'shadow-1-left',
    'boxShadowDrawerRight': 'shadow-1-right',
};
