import {ThemeConfig} from 'antd';
import acudMatricsTokens from '@osui/icloud-theme/es/theme/acud/matrics';
import acudSemanticTokens from '@osui/icloud-theme/es/theme/acud/acud-semantic-token';

export const components: ThemeConfig['components'] = {
    Button: {
        paddingContentHorizontal: parseInt(acudMatricsTokens['--space-s'], 10),
        borderRadius: parseInt(acudMatricsTokens['--radius-xs'], 10),
        borderRadiusSM: parseInt(acudMatricsTokens['--radius-2xs'], 10),
        borderRadiusLG: parseInt(acudMatricsTokens['--radius-xs'], 10),
        paddingInline: parseInt(acudMatricsTokens['--space-m'], 10),
        paddingInlineSM: parseInt(acudMatricsTokens['--space-2xs'], 10),
        paddingInlineLG: parseInt(acudMatricsTokens['--space-xl'], 10),
        marginXS: parseInt(acudMatricsTokens['--radius-2xs'], 10),
    },
    Divider: {
        colorSplit: 'rgba(0, 0, 0, 0.06)',
    },
    Input: {
        paddingInline: 12,
        colorFillAlter: acudSemanticTokens['--bg-color-white'],
        colorTextPlaceholder: acudSemanticTokens['--text-color-disabled'],
        colorBorder: acudSemanticTokens['--component-color-border'],
        hoverBorderColor: acudSemanticTokens['--brand-color'],
        activeBorderColor: acudSemanticTokens['--brand-color-active'],
        activeShadow: `0 0 0 1px ${acudSemanticTokens['--brand-color-light-active']}`,
        colorBgContainerDisabled: acudSemanticTokens['--component-color-grayB-disable'],
        colorTextDisabled: acudSemanticTokens['--text-color-tertiary'],
        colorTextDescription: acudSemanticTokens['--text-color-tertiary'],
        borderRadius: parseInt(acudMatricsTokens['--radius-xs'], 10),
        controlHeight: parseInt(acudMatricsTokens['--component-height-xl'], 10),
        controlHeightSM: parseInt(acudMatricsTokens['--component-height-l'], 10),
        controlHeightLG: parseInt(acudMatricsTokens['--component-height-2xl'], 10),
        fontSize: parseInt(acudMatricsTokens['--font-size-xs'], 10),
        fontSizeSM: parseInt(acudMatricsTokens['--font-size-2xs'], 10),
        fontSizeLG: parseInt(acudMatricsTokens['--font-size-s'], 10),
    },
    InputNumber: {
        paddingInline: 12,
        colorFillAlter: acudSemanticTokens['--bg-color-white'],
        colorTextPlaceholder: acudSemanticTokens['--text-color-disabled'],
        colorBorder: acudSemanticTokens['--component-color-border'],
        hoverBorderColor: acudSemanticTokens['--brand-color'],
        activeBorderColor: acudSemanticTokens['--brand-color-active'],
        activeShadow: `0 0 0 1px ${acudSemanticTokens['--brand-color-light-active']}`,
        colorBgContainerDisabled: acudSemanticTokens['--component-color-grayB-disable'],
        colorTextDisabled: acudSemanticTokens['--text-color-tertiary'],
        colorTextDescription: acudSemanticTokens['--text-color-tertiary'],
        borderRadius: parseInt(acudMatricsTokens['--radius-xs'], 10),
        controlHeight: parseInt(acudMatricsTokens['--component-height-xl'], 10),
        controlHeightSM: parseInt(acudMatricsTokens['--component-height-l'], 10),
        controlHeightLG: parseInt(acudMatricsTokens['--component-height-2xl'], 10),
        fontSize: parseInt(acudMatricsTokens['--font-size-xs'], 10),
        fontSizeSM: parseInt(acudMatricsTokens['--font-size-2xs'], 10),
        fontSizeLG: parseInt(acudMatricsTokens['--font-size-s'], 10),
    },
    Alert: {
        colorInfoBorder: '#E6F0FF',
        colorInfoBg: '#E6F0FF',
        colorWarningBorder: '#FFF4E6',
        colorWarningBg: '#FFF4E6',
        colorSuccessBorder: '#ECFFE6',
        colorSuccessBg: '#ECFFE6',
        colorErrorBorder: '#FFE8E6',
        colorErrorBg: '#FFE8E6',
        lineHeight: 1.5,
        fontSize: 12,
    },
    Modal: {
        paddingMD: 0,
        paddingContentHorizontalLG: 0,
        marginXS: 0,
        marginSM: 0,
        lineHeightHeading5: 1.375,
        lineHeight: 1.5,
        fontSize: 12,
        paddingLG: 24,
        fontSizeLG: 16,
        fontWeightStrong: 500,
    },
    Select: {
        paddingSM: 13,
        fontWeightStrong: 400,
        controlHeightSM: 24,
        borderRadiusSM: parseInt(acudMatricsTokens['--radius-xs'], 10),
    },
    Anchor: {
        fontSize: 12,
        colorSplit: '#E8E9EB',
    },
    DatePicker: {
        paddingSM: 13,
        boxShadowSecondary: `0 3px 6px -4px rgba(0, 0, 0, 0.12),
            0 6px 16px 0 rgba(0, 0, 0, 0.08),
            0 9px 28px 8px rgba(0, 0, 0, 0.05)`,
    },
    Pagination: {
        marginXS: 0,
        controlHeightSM: 32,
        borderRadius: parseInt(acudMatricsTokens['--radius-xs'], 10),
        colorTextDisabled: acudSemanticTokens['--text-color-disabled'],
        colorBgContainerDisabled: acudSemanticTokens['--component-color-grayB1'],
    },
    Steps: {
        controlHeight: 26,
        fontSize: 14,
        controlItemBgActive: '#FFF',
        colorTextDescription: acudSemanticTokens['--text-color-tertiary'],
        colorText: acudSemanticTokens['--text-color-primary'],
        marginXS: 10,
        controlHeightLG: 42,
        colorFillContent: '#FFF',
    },
    Table: {
        colorFillAlter: '#F7F7F9',
        padding: 10,
        paddingContentVerticalLG: 11,
        colorTextHeading: '#5C5F66',
        paddingXS: 5.5,
        bodySortBg: 'transparent',
        headerSortActiveBg: '#f7f7f9',
    },
    Tooltip: {
        colorBgBase: '#fff',
        // antd 5 在某个版本之后更改了 token 名
        colorBgSpotlight: '#fff',
        colorTextLightSolid: '#151B26',
        borderRadius: parseInt(acudMatricsTokens['--radius-xs'], 10),
        boxShadowSecondary: acudMatricsTokens['--drop-shadow-m'],
        fontSize: parseInt(acudMatricsTokens['--font-size-2xs'], 10),
        lineHeight: parseInt(acudMatricsTokens['--font-height-2xs'], 10) / 10,
    },
    Tabs: {
        fontSize: 14,
        lineWidthFocus: 0,
        colorText: acudSemanticTokens['--text-color-secondary'],
        itemHoverColor: acudSemanticTokens['--text-color-secondary'],
        horizontalItemPadding: '4px 0px',
        cardGutter: 8,
    },
    Breadcrumb: {
        colorBgTextHover: 'transparent',
        colorTextDescription: '#5c5f66',
    },
    Menu: {
        colorItemTextHover: '#2468F2',
        colorItemBgHover: 'transparent',
        borderRadiusLG: 0,
        marginXXS: 0,
    },
    Tag: {
        lineHeight: parseInt(acudMatricsTokens['--component-height-2xs'], 10),
        colorFillQuaternary: '#F7F7F9',
        defaultColor: acudSemanticTokens['--text-color-secondary'],
        defaultBg: acudSemanticTokens['--component-color-grayB1'],
        colorBorder: acudSemanticTokens['--component-color-grayB-active'],
        fontSize: parseInt(acudMatricsTokens['--font-size-2xs'], 10),
    },
    Result: {
        fontSizeHeading3: 24,
        colorTextDescription: '#5C5F66',
        marginXS: 0,
        lineHeightHeading3: 1.8,
        lineHeight: 1.6,
    },
    Upload: {
        colorFillAlter: '#fff',
    },
    Avatar: {
        controlHeightSM: 21,
        containerSizeLG: 32,
        containerSize: 24,
        containerSizeSM: 16,
        // fontSize: 12,
    },
    Checkbox: {
        marginXS: 0,
    },
    Layout: {
        colorBgBody: '#F7F7F9',
    },
    Switch: {
        handleSize: 11,
    },
    Dropdown: {
        borderRadiusSM: parseInt(acudMatricsTokens['--radius-2xs'], 10),
        controlItemBgHover: acudSemanticTokens['--component-color-grayB2'],
    },
};

