// 把antd的css vars映射到osui theme的
export default {
    '--primary-color': 'var(--theme-primary-color)',
    '--primary-color-hover': 'var(--theme-primary-color)', // 这个颜色用在select选中的颜色，感觉不太对
    '--info-color': 'var(--theme-info-color)',
    '--success-color': 'var(--theme-success-color)',
    '--error-color': 'var(--theme-error-color)',
    '--warning-color': 'var(--theme-warning-color)',
    '--primary-1': '#111b26',
    '--primary-2': '#11263c',
    '--primary-5': '#165996',
    '--primary-6': '#177ddc',
    '--primary-7': '#388ed3',
    '--body-background': 'var(--theme-body-bg)',
    '--border-color-base': 'var(--theme-border-color-base)',
    '--border-color-inverse': 'var(--theme-border-color-inverse)',
    '--border-color-split': 'var(--theme-border-color-split)',
    '--background-color-base': 'var(--theme-bg-color-base)',
    '--background-color-light': 'var(--theme-bg-color-light)',
    '--component-background': 'var(--theme-component-bg)',
    '--disabled-bg': 'var(--theme-disabled-bg)',
    '--disabled-color': 'var(--theme-disabled-color)',
    '--heading-color': 'var(--theme-heading-color)',
    '--item-active-bg': 'var(--theme-secondary-color-hover)',
    '--label-color': 'rgba(255, 255, 255, 0.85)',
    '--link-color': 'var(--theme-primary-color)',
    '--link-hover-color': '#165996',
    '--link-active-color': '#388ed3',
    '--outline-color': 'var(--theme-border-focus-color)',
    '--highlight-color': 'var(--red-5)',
    '--text-color-inverse': '#fff',
    '--item-hover-bg': 'rgba(255, 255, 255, 0.08)',

};
