export default {
    // eslint-disable-next-line max-len
    '--theme-font-family': '-apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", "Arial", "PingFangSC-Regular", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
    '--theme-bg-color-base': 'rgba(255, 255, 255, 0.08)',
    '--theme-bg-color-light': 'rgba(255, 255, 255, 0.04)',
    '--theme-body-bg': '#000',
    '--theme-border-color-base': '#434343',
    '--theme-border-color-disabled': 'var(--color-gray-5)',
    '--theme-border-color-inverse': '#fff',
    '--theme-border-color-split': '#303030',
    '--theme-border-focus-color': 'var(--theme-primary-color)',
    '--theme-color-text': 'var(--color-gray-8)',
    '--theme-component-bg': '#141414',
    '--theme-component-focus-box-shadow': 'none',
    '--theme-disabled-bg': 'rgba(255, 255, 255, 0.08)',
    '--theme-disabled-color': 'rgba(255, 255, 255, 0.3)',
    '--theme-error-color-active': 'var(--color-error-7)',
    '--theme-error-color-hover': 'var(--color-error-5)',
    '--theme-error-color': 'var(--color-error-6)',
    '--theme-heading-color': 'rgba(255, 255, 255, 0.85)',
    '--theme-highlight-color': '#a61d24',
    '--theme-icon-color': 'var(--color-gray-7)',
    '--theme-info-color-active': 'var(--color-info-7)',
    '--theme-info-color-hover': 'var(--color-info-5)',
    '--theme-info-color': '#177ddc',
    '--theme-outline-color': '#177ddc',
    '--theme-placeholder-color': 'var(--color-gray-7)',
    '--theme-primary-color-active': 'var(--color-brand-7)',
    '--theme-primary-color-hover': '#3c9be8',
    '--theme-primary-color': '#177ddc',
    '--theme-processing-color': 'var(--color-brand-6)',
    '--theme-secondary-color-active': 'var(--color-brand-3)',
    '--theme-secondary-color-hover': 'var(--color-brand-1)',
    '--theme-secondary-color': '#111b26',
    '--theme-success-color-active': 'var(--color-success-7)',
    '--theme-success-color-hover': 'var(--color-success-5)',
    '--theme-success-color': '#49aa19',
    '--theme-text-color-secondary': 'var(--color-gray-8)',
    '--theme-text-color': 'var(--color-gray-9)',
    '--theme-warning-color-active': 'var(--color-warning-7)',
    '--theme-warning-color-hover': 'var(--color-warning-5)',
    '--theme-warning-color': '#d89614',
    '--item-hover-bg': 'var(--color-gray-3)',
    '--osui-icon-size': '16px',

};
