export default {
    '--checkbox-border-color': 'var(--theme-border-color-base)',
    '--checkbox-hover-bg': 'var(--color-gray-3)',
    '--checkbox-hover-border-color': 'var(--theme-border-color-base)',
    '--checkbox-focus-bg': 'var(--color-gray-1)',
    '--checkbox-active-border-color': 'var(--theme-border-color-base)',
    '--checkbox-disabled-bg': 'var(--color-gray-1)',
    '--checkbox-disabled-border-color': 'var(--theme-border-color-disabled)',
    '--checkbox-disabled-color': 'var(--theme-disabled-color)',
    '--checkbox-checked-bg': 'var(--theme-primary-color)',
    '--checkbox-checked-border-color': 'transparent',
    '--checkbox-checked-hover-bg': 'var(--theme-primary-color-hover)',
    '--checkbox-checked-hover-border-color': 'var(--theme-primary-color-hover)',
    '--checkbox-checked-focus-bg': 'var(--theme-primary-color)',
    '--checkbox-checked-focus-border-color': 'var(--theme-border-color-base)',
    '--checkbox-checked-focus-box-shadow': 'var(--theme-component-focus-box-shadow)',
    '--checkbox-checked-disabled-bg': 'var(--color-gray-1)',
    '--checkbox-checked-disabled-border-color': 'var(--theme-border-color-disabled)',

    '--checkbox-padding-horizontal': '8px',
    '--checkbox-group-item-margin-right': '8px',
    '--checkbox-border-radius': '4px',
};
