export default {
    '--collapse-content-bg': 'var(--theme-component-bg)',
    '--collapse-header-bg': 'var(--color-gray-2)',
    '--collapse-disabled-color': 'var(--theme-disabled-color)',
    '--collapse-expand-icon-color': 'var(--theme-text-color)',
    '--collapse-expand-icon-bg': 'var(--color-gray-3)',
    '--collapse-border-color': '1px solid var(--theme-border-color-base)',
    '--collapse-bg': 'var(--collapse-header-bg)',
    '--collapse-header-font-weight': '600',
    '--collapse-header-font-size': '14px',
    '--collapse-header-height': '32px',
    '--collapse-content-box-padding-top': '8px',
    '--collapse-content-box-padding-bottom': '8px',
    '--collapse-arrow-top': '7px',
    '--collpase-item-header-margin-bottom': '0px',
};
