export default {
    '--pagination-item-border-color': 'var(--color-gray-5)',
    '--pagination-item-hover-bg': 'var(--color-gray-3)',
    '--pagination-item-hover-color': 'var(--theme-text-color)',
    '--pagination-item-hover-border-color': 'var(--color-gray-5)',
    '--pagination-item-active-border-color': 'var(--color-brand-1)',
    '--pagination-item-active-bg': 'var(--color-brand-1)',
    '--pagination-item-active-color': 'var(--color-brand-7)',
    '--pagination-item-disabled-border-color': 'var(--btn-disable-border)',
    '--pagination-disabled-bg': 'var(--btn-disable-bg)',
    '--pagination-prev-next-icon-color': 'var(--theme-text-color)',
    '--pagination-prev-next-icon-color-disabled': 'var(--theme-disabled-color)',
    '--pagination-item-margin-right': '8px',
    '--pagination-prev-next-border': '1px solid var(--pagination-item-border-color)',
};
