export default {
    '--tag-check-border': 'var(--color-brand-4)',
    '--tag-default-bg': 'var(--color-gray-3)',
    '--tag-font-color': 'var(--color-gray-9)',
    '--tag-blue-color': 'var(--color-brand-2)',
    '--tag-green-color': 'var(--color-success-1)',
    '--tag-purple-color': 'var(--color-purple-1)',
    '--tag-red-color': 'var(--color-error-1)',
    '--tag-yellow-color': 'var(--color-warning-1)',
    '--tag-blue-bg-color': 'var(--tag-blue-color)',
    '--tag-blue-font-color': 'var(--tag-font-color)',
    '--tag-blue-solid-bg-color': 'var(--tag-blue-color)',
    '--tag-green-bg-color': 'var(--tag-green-color)',
    '--tag-green-font-color': 'var(--tag-font-color)',
    '--tag-green-solid-bg-color': 'var(--tag-green-color)',
    '--tag-red-bg-color': 'var(--tag-red-color)',
    '--tag-red-solid-bg-color': 'var(--tag-red-color)',
    '--tag-red-font-color': 'var(--tag-font-color)',
    '--tag-yellow-bg-color': 'var(--tag-yellow-color)',
    '--tag-yellow-solid-bg-color': 'var(--tag-yellow-color)',
    '--tag-yellow-font-color': 'var(--tag-font-color)',
    '--tag-padding': '0 7px',
    '--tag-icon-color': 'var(--theme-text-color)',
    '--tag-icon-maring-horizontal': '4px',
};
