export default {
    // 圆角
    '--border-radius-1': '0px',
    '--border-radius-2': '2px',
    '--border-radius-3': '4px',
    '--border-radius-4': '6px',
    '--border-radius-5': '8px',
    '--border-radius-6': '10px',
    '--border-radius-7': '16px',
    '--border-radius-8': '50%',
    '--border-radius-base': 'var(--border-radius-3)',
    '--border-radius-sm': 'var(--border-radius-2)',
    /* radius 圆角 */
    '--radius-3xs': '2px',
    '--radius-2xs': '4px',
    '--radius-xs': '6px',
    '--radius-s': '8px',
    '--radius-m': '10px',
    '--radius-l': '12px',
    '--radius-xl': '16px',
    '--radius-2xl': '18px',
    '--radius-3xl': '20px',
    '--radius-4xl': '24px',
    /* space 间距 */
    '--space-3xs': '4px',
    '--space-2xs': '8px',
    '--space-xs': '10px',
    '--space-s': '12px',
    '--space-m': '16px',
    '--space-l': '20px',
    '--space-xl': '24px',
    '--space-2xl': '32px',
    '--space-3xl': '40px',
    '--space-4xl': '48px',
    /* drop shadow 阴影 */
    '--drop-shadow-xs': `
        0 0 0 1px rgba(24, 24, 27, 0.07)
        0 1px 2px 0 rgba(24, 24, 27, 0.15)
        0 2px 4px 0 rgba(24, 24, 27, 0.07)`,
    '--drop-shadow-s': '0 4px 12px 0 rgba(0, 25, 126, 0.02)',
    '--drop-shadow-m': '0 2px 10px 0 rgba(0, 25, 126, 0.08)',
    '--drop-shadow-l': '0 2px 20px 0 rgba(0, 25, 126, 0.10)',
    /* inner shadow 内阴影 */
    '--inner-shadow-xs': '0 2px 0 0 var(--b-6333-aff, #333AFF) inset',
    /* font size 字号 */
    '--font-size-3xs': '10px',
    '--font-size-2xs': '12px',
    '--font-size-xs': '13px',
    '--font-size-s': '14px',
    '--font-size-m': '16px',
    '--font-size-l': '18px',
    '--font-size-xl': '20px',
    '--font-size-2xl': '24px',
    '--font-size-3xl': '28px',
    '--font-size-4xl': '32px',
    '--font-size-5xl': '36px',
    '--font-size-6xl': '40px',
    /* font weight 字重 */
    '--font-weight-regular': '400',
    '--font-weight-medium': '500',
    '--font-weight-semibold': '600',
    /* font height 字行高 */
    '--font-height-3xs': '16px',
    '--font-height-2xs': '18px',
    '--font-height-xs': '20px',
    '--font-height-s': '22px',
    '--font-height-m': '24px',
    '--font-height-l': '28px',
    '--font-height-xl': '30px',
    '--font-height-2xl': '36px',
    '--font-height-3xl': '42px',
    '--font-height-4xl': '48px',
    '--font-height-5xl': '54px',
    '--font-height-6xl': '60px',
    /* paragraph height 段落行高 */
    '--paragraph-height-xs': '22',
    '--paragraph-height-s': '24',
    '--paragraph-height-m': '26',
    '--paragraph-height-l': '30',
    /* component height 组件高度 */
    '--component-height-3xs': '8px',
    '--component-height-2xs': '14px',
    '--component-height-xs': '16px',
    '--component-height-s': '18px',
    '--component-height-m': '20px',
    '--component-height-l': '24px',
    '--component-height-x|': '32px',
    '--component-height-2xl': '40px',
    '--component-height-3xl': '60px',
    '--component-height-4xl': '78px',
};
