// 把antd的css vars映射到osui theme的
export default {
    '--primary-color': 'var(--theme-primary-color)',
    '--primary-color-hover': 'var(--theme-primary-color-active)', // 因为antd的focus状态用的是hover color，见 input mixin
    '--primary-color-active': 'var(--theme-primary-color)', // 这两个都是antd自身的用法，我们会直接用css vars来使用，这里不区分active hover
    '--info-color': 'var(--theme-info-color)',
    '--success-color': 'var(--theme-success-color)',
    '--error-color': 'var(--theme-error-color)',
    '--warning-color': 'var(--theme-warning-color)',
    '--primary-1': '#eef0fd',
    '--primary-2': '#dce1fa',
    '--primary-5': '#7387eb',
    '--primary-7': '#5971e7',
    '--body-background': 'var(--theme-body-bg)',
    '--border-color-base': 'var(--theme-border-color-base)',
    '--border-color-inverse': 'var(--theme-border-color-inverse)',
    '--border-color-split': 'var(--theme-border-color-split)',
    '--background-color-base': 'var(--theme-bg-color-base)',
    '--background-color-light': 'var(--theme-bg-color-light)',
    '--component-background': 'var(--theme-component-bg)',
    '--disabled-bg': 'var(--theme-disabled-bg)',
    '--disabled-color': 'var(--theme-disabled-color)',
    '--heading-color': 'var(--theme-heading-color)',
    '--item-active-bg': 'var(--theme-secondary-color-hover)',
    '--label-color': 'var(--color-gray-8)',
    '--link-active-color': 'var(--theme-primary-color-active)',
    '--link-color': 'var(--theme-primary-color)',
    '--link-hover-color': 'var(--theme-primary-color-hover)',
    '--outline-color': 'var(--theme-border-focus-color)',
    '--highlight-color': 'var(--color-error-6)',
    '--primary-6': 'var(--primary-color)',
    '--text-color-inverse': '#fff',
    '--white': '#fff',
    '--black': '#000',
    '--normal-color': '#d9d9d9',
    '--error-color-active': 'var(--color-error-7)',
    '--error-color-hover': 'var(--color-error-5)',
    '--error-color-outline': 'rgba(255, 77, 79, 0.2)',
    '--error-color-deprecated-bg': '#fff2f0',
    '--error-color-deprecated-border': '#ffccc7',
    '--success-color-active': 'var(--color-success-7)',
    '--success-color-hover': 'var(--color-success-5)',
    '--success-color-outline': 'rgba(82, 196, 26, 0.2)',
    '--success-color-deprecated-bg': '#f6ffed',
    '--success-color-deprecated-border': '#b7eb8f',
    '--warning-color-active': 'var(--color-warning-7)',
    '--warning-color-hover': 'var(--color-warning-5)',
    '--warning-color-deprecated-bg': '#fffbe6',
    '--warning-color-deprecated-border': '#ffe58f',
    '--warning-color-outline': 'rgba(250, 173, 20, 0.2)',
};
