export default {
    // eslint-disable-next-line max-len
    '--theme-font-family': '-apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", "Arial", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", "sans-serif", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
    '--theme-bg-color-base': 'var(--gray-color-4)',
    '--theme-bg-color-light': 'var(--brand-color-1)',
    '--theme-body-bg': 'var(--gray-color-2)',
    '--theme-border-color-base': 'var(--gray-color-4)',
    '--theme-border-color-disabled': 'var(--gray-color-4)',
    '--theme-border-color-inverse': '#fff',
    '--theme-border-color-split': 'var(--gray-color-4)',
    '--theme-border-focus-color': 'var(--theme-primary-color)',
    '--theme-color-text': 'var(--gray-color-8)',
    '--theme-component-bg': 'var(--gray-color-1)',
    '--theme-component-focus-box-shadow': 'none',
    '--theme-disabled-bg': 'var(--gray-color-2)',
    '--theme-disabled-color': 'var(--grayB-color-5)',
    '--theme-error-color-active': 'var(--error-color-active)',
    '--theme-error-color-hover': 'var(--error-color-hover)',
    '--theme-error-color': 'var(--error-color)',
    '--theme-heading-color': 'var(--gray-color-9)',
    '--theme-highlight-color': 'var(--error-color-hover)',
    '--theme-icon-color': 'var(--gray-color-7)',
    '--theme-info-color-active': 'var(--color-info-7)',
    '--theme-info-color-hover': 'var(--color-info-5)',
    '--theme-info-color': 'var(--color-info-6)',
    '--theme-outline-color': 'var(--brand-color-4)',
    '--theme-placeholder-color': 'var(--gray-color-6)',
    '--theme-primary-color-active': 'var(--brand-color-7)',
    '--theme-primary-color-hover': 'var(--brand-color-5)',
    '--theme-primary-color': 'var(--brand-color-6)',
    '--theme-processing-color': 'var(--brand-color-6)',
    '--theme-secondary-color-active': 'var(--brand-color-3)',
    '--theme-secondary-color-hover': 'var(--brand-color-1)',
    '--theme-secondary-color': 'var(--brand-color-2)',
    '--theme-success-color-active': 'var(--success-color-active)',
    '--theme-success-color-hover': 'var(--success-color-hover)',
    '--theme-success-color': 'var(--success-color)',
    '--theme-text-color-secondary': 'var(--gray-color-8)',
    '--theme-text-color': 'var(--gray-color-9)',
    '--theme-warning-color-active': 'var(--warning-color-active)',
    '--theme-warning-color-hover': 'var(--warning-color-hover)',
    '--theme-warning-color': 'var(--warning-color)',
    '--item-hover-bg': 'var(--brand-color-1)',
    '--osui-icon-size': '16px',
};
