export default {
    // eslint-disable-next-line max-len
    '--theme-font-family': '"Helvetica Neue", "Helvetica", "Arial", "PingFangSC-Regular", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", "sans-serif"',
    '--theme-bg-color-base': 'var(--color-gray-4)',
    '--theme-bg-color-light': 'var(--color-brand-1)',
    '--theme-body-bg': 'var(--color-gray-1)',
    '--theme-border-color-base': 'var(--color-gray-5)',
    '--theme-border-color-inverse': '#fff',
    '--theme-border-color-split': 'var(--color-gray-4)',
    '--theme-border-color-disabled': 'var(--color-gray-4)',
    '--theme-component-bg': 'var(--color-gray-1)',
    '--theme-component-focus-box-shadow': '0 0 0 1px var(--theme-border-focus-color)',
    '--theme-disabled-bg': 'var(--color-gray-4)',
    '--theme-disabled-color': 'var(--color-gray-6)',
    '--theme-error-color-active': 'var(--color-error-5)',
    '--theme-error-color-hover': 'var(--color-error-5)',
    '--theme-error-color': 'var(--color-error-5)',
    '--theme-heading-color': 'var(--theme-text-color)',
    '--theme-info-color-active': 'var(--color-info-5)',
    '--theme-info-color-hover': 'var(--color-info-5)',
    '--theme-info-color': 'var(--color-info-5)',
    '--theme-primary-color-active': 'var(--color-brand-6)',
    '--theme-primary-color-hover': 'var(--color-brand-6)',
    '--theme-primary-color': 'var(--color-brand-6)',
    '--theme-secondary-color-active': 'var(--color-brand-3)',
    '--theme-secondary-color-hover': 'var(--color-brand-1)',
    '--theme-secondary-color': 'var(--color-brand-2)',
    '--theme-success-color-active': 'var(--color-success-5)',
    '--theme-success-color-hover': 'var(--color-success-5)',
    '--theme-success-color': 'var(--color-success-5)',
    '--theme-text-color-secondary': 'var(--color-gray-8)',
    '--theme-text-color': 'var(--color-gray-9)',
    '--theme-placeholder-color': 'var(--color-gray-7)',
    '--theme-warning-color-active': 'var(--color-warning-5)',
    '--theme-warning-color-hover': 'var(--color-warning-5)',
    '--theme-warning-color': 'var(--color-warning-5)',
    '--theme-color-text': 'var(--color-gray-8)',
    '--theme-highlight-color': 'var(--color-error-5)',
    '--theme-outline-color': 'var(--color-brand-4)',
    '--theme-processing-color': 'var(--color-brand-6)',
    '--theme-border-focus-color': 'var(--color-brand-4)',
    '--theme-icon-color': 'var(--theme-text-color)',
    '--shadow-1': '0 4px 8px -2px rgba(9, 30, 66, 0.25), 0 0 1px 0 rgba(9, 30, 66, 0.31)', // 和antd的shadow-1的不一样，用于气泡
    '--shadow-2': '0 8px 16px -4px rgba(9, 30, 66, 0.25)',
    '--item-hover-bg': 'var(--color-gray-3)',
    '--osui-icon-size': '16px',
};
